# pos
# Assuming the origin is at the 3D geometric center of the robot, use the following frame axis convention:
#   x: positive right
#   y: positive forwards
#   z: positive up
# Define your camera locations using the above axis. For example, a camera on the front of the robot (50cm from the center
# of the robot), centered left-right, mounted on a pole 25cm above the midpoint of the robot looking upwards
# at a 20 degree angle:
# translation: [0.0, 0.5, 0.25] # x,y,z
# rotation: [0, 20, 0] # roll, pitch, yaw
# For the same configuration, but at the back of the robot looking backwards:
# translation: [0, -0.5, 0.25] # x,y,z
# rotation: [0, 20, 180] # roll, pitch, yaw

Team number: -1
Fmap file: ../stereo14_6.fmap

#Video recording: true
Pose logging: true

Cameras:
  # front left
  CAM_LEFT:
    camera_id: 4
#    camera_playback_file: CAM_LEFT.mp4

    rx: 544
    ry: 288

    fx: 600
    fy: 600
    # x,y,z
    translation: [-0.10, 0, 0]
#    translation: [0, 0, 0]
    # roll, pitch, yaw
    rotation: [0, 0, 0]
#    res_x: 640
#    res_y: 360
    fps: 30.0
    exposure: 1

  CAM_RIGHT:
    camera_id: 2
#    camera_playback_file: CAM_RIGHT.mp4
    rx: 544
    ry: 288
    fx: 600
    fy: 600
    # x,y,z
    translation: [0.10, 0, 0]
    # roll, pitch, yaw
    rotation: [0, 0, 0]
    fps: 30.0
    exposure: 1

  # backwards facing cam
  CAM_REAR:
    camera_id: 0
#    camera_playback_file: CAM_REAR.mp4
    rx: 544
    ry: 288
    fx: 600
    fy: 600
    # x,y,z
    translation: [-0.02, -0.305, 0]
    # roll, pitch, yaw
    rotation: [0, 0, 180]
    fps: 30.0
    exposure: 1