
services:
  ampl:
    image: rogueraptor7/ampl:latest
    volumes:
      - ./config.yml:/app/AMPL/config.yml
      - ./logs:/app/AMPL/build/logs
      - ./field.fmap:/app/AMPL/fmap/field.fmap
    restart: always
    privileged: true
    network_mode: host
    tty: true
    command: bash -c "./ampl 2>&1 | grep -v \"Corrupt JPEG data\""