name: ampl

services:
  ampl:
    image: rogueraptor7/ampl:latest
    volumes:
      - ./config.yml:/app/AMPL/config.yml
      - ./ampl_log.txt:/app/AMPL/build/ampl_log.txt
    restart: always
    privileged: true
    network_mode: host
    tty: true
    command:
      - ./ampl 2>&1 | grep -v "Corrupt JPEG data"