
services:
  maple:
    image: rogueraptor7/maple:latest
    volumes:
      - ./config.yml:/app/MAPLE/config.yml
      - ./logs:/app/MAPLE/build/logs
      - ./field.fmap:/app/MAPLE/fmap/field.fmap
    restart: always
    privileged: true
    network_mode: host
    tty: true
    command: bash -c "./maple 2>&1 | grep -v \"Corrupt JPEG data\""