name: ampl

services:
  ampl:
    image: rogueraptor7/ampl:latest
    volumes:
      - ./config.yml:/app/AMPL/config.yml
      - ./ampl_logs:/app/AMPL/build/logs
    restart: always
    privileged: true
    network_mode: host
    tty: true
    command: bash -c "./ampl 2>&1 | grep -v \"Corrupt JPEG data\""