tests:
  center_of_field:
    fmap: ../fmap/field.fmap
    camera_names:
      - left
      - right
      - rear
    camera_extrinsics:
      - [0,0,0,0,0,0]
      - [0.5,0.5,0,0,0,-30]
      - [0,0,0,0,0,180]
    waypoints:
      - [0,1.0,0.5,0.5,0,15,-90]
      - [3,0.0,0.5,0.5,0,15,-90]
      - [6,0.0,1.5,0.5,0,15,-90]
      - [9,0.0,0.5,0.5,0,15,-90]
      - [12,1.0,0.5,0.5,0,15,-90]
      - [15,1.0,0.5,0.5,0,15,-90]