# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docs:
    runs-on: X64
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Build docs
        shell: bash
        run: cd docs; bash generate-docs.sh
