# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Pull code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run build and test script
      shell: bash
      run: cd docker; bash ci-build-image.sh
