# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ci-tests-job:
    runs-on: ubuntu-latest

    steps:
    - name: Pull code
      uses: actions/checkout@v4

    - name: Run build and test script
      shell: bash
      run: bash ci-tests.sh
