# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Run tests

on:
  push:
    branches: [ "main" ]
    paths: [ "include/**", "src/**", "lib/**", "test/**", "CMakeLists.txt", ".github/workflows/build-and-test.yml" ]

  pull_request:
    branches: [ "main" ]
    paths: [ "include/**", "src/**", "lib/**", "test/**", "CMakeLists.txt", ".github/workflows/build-and-test.yml" ]


jobs:
  ci-x86-tests:
    runs-on: X64
    timeout-minutes: 20

    steps:
    - name: Pull code
      uses: actions/checkout@v4

    - name: x86 tests
      shell: bash
      run: bash ci-tests.sh
  ci-ARM64-tests:
    runs-on: ARM64
    timeout-minutes: 20
  
    steps:
      - name: Pull code
        uses: actions/checkout@v4
  
      - name: ARM64 tests
        shell: bash
        run: bash ci-tests.sh
