# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ci-x86-tests-job:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Pull code
      uses: actions/checkout@v4

    - name: x86 tests
      shell: bash
      run: bash ci-tests.sh

  run-ci-ARM64-tests-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: ARM64 tests
        shell: bash
        run: ARM=1 bash ci-tests.sh
